# Generated by Django 4.2.6 on 2023-12-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='FName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='LName',
            new_name='Last_Name',
        ),
    ]
