# Generated by Django 4.2.6 on 2023-12-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=15)),
                ('Salary', models.IntegerField()),
                ('Placr', models.CharField(max_length=25)),
            ],
        ),
    ]
